
trigger:
- main  
pool:
      name: Default
      demands:
       - agent.os -equals Linux 

variables:
- name: containerName
  value: kolahduzan-catalog

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Regis Cloudware'
    repository: 'cloudware/$(containerName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)
      latest

